name: Deploy documentation

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: Install npm dependencies 
      run: cd docs && npm install
    
    - name: Run tests
      continue-on-error: false
      run: npm run test
      
    - name: Deploy pages
      run: npm run deploy:githubpages
