name: Deploy documentation

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        path: ./docs
      
    - name: Set Node.js version
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: Install npm dependencies 
      run: npm install
    
    - name: Run tests
      continue-on-error: false
      run: npm run test
      
    - name: Deploy pages
      run: gatsby build --prefix-paths && gh-pages -d public -r https://${{ secrets.GH_TOKEN }}@github.com/losol/Losol.Communication.git"
