name: Deploy Nuget package

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.103
    - name: Run tests
      run: dotnet test
    - name: Pack NuGet Packages
      run: dotnet pack ./src/Email/Losol.Communication.Email.csproj --configuration Release -o NuGetPackages
    - name: Deploy Nuget Packages
      run: dotnet nuget push ./**/*.nupkg 
        --api-keyk ${{ secrets.NUGET_API_KEY }} 
        --source https://api.nuget.org/v3/index.json
